name: Build AOT .NET Project for Windows

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build -c Release

      - name: Publish AOT for Windows
        run: dotnet publish -c Release

      - name: GH Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: ./bin/Release/net8.0/win-x64/publish/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}          

      - name: Archive the build
        uses: actions/upload-artifact@v4
        with:
          name: windows-aot-build
          path: ./bin/Release/net10.0/win-x64/publish/